"""User-facing copy. Callback identifiers are independent of translated labels."""

HELLO = (
    "Привет! Я помогу добавлять еду в дневник FatSecret по фото или описанию.\nВыберите язык.\n\n"
    "Сервис предназначен для пользователей 18+.\n\n"
    "Hi! I can add meals to your FatSecret diary from a photo or description.\nChoose your language.\n\n"
    "This service is for users aged 18 and over."
)
LANGUAGE_PROMPT = "Выберите язык / Choose your language:"

TEXTS = {
    "ru": {
        "matching_uncertain": "Не удалось надёжно подобрать продукт и порцию в FatSecret. Ничего не записано. Отправьте блюдо заново, указав название, бренд и вес.",
        "meal_expired": "Черновик блюда удалён. Отправьте фото или описание заново.",
        "daily_limit_reached": "На сегодня лимит добавлений исчерпан. Попробуйте снова завтра.\n\nЧерновик хранится ещё 30 минут ожидания, затем его нужно отправить заново.",
        "service_retry": "Сервис анализа временно перегружен. Подожду и повторю запрос автоматически: попытка {attempt} из {total}.",
        "service_busy": "Сервис анализа временно перегружен или достигнут лимит запросов. Автоматические повторы не помогли. В FatSecret ничего не записано.\n\nЧерновик хранится ещё 30 минут ожидания. Попробуйте позже кнопкой «Распознать и добавить» или отмените добавление.",
        "add": "Добавить еду", "menu_button": "Главное меню", "settings_button": "Настройки",
        "cancel_meal": "Отменить добавление",
        "approve": "Мне есть 18 — распознать", "resend": "Отправить другое",
        "write_entries": "Записать в FatSecret",
        "breakfast": "Завтрак", "lunch": "Обед", "dinner": "Ужин", "other": "Перекус",
        "connect": "Подключить FatSecret", "open_fatsecret": "Открыть FatSecret",
        "disconnect": "Отключить FatSecret", "disconnect_yes": "Отключить",
        "disconnect_no": "Оставить подключённым", "language_button": "Язык",
        "connected": "подключён", "disconnected": "не подключён",
        "menu": "Главное меню\n\nОтправьте фото, описание блюда или фото с подписью. После анализа проверьте продукты, порции и КБЖУ, затем отдельно подтвердите запись.\n\nПример: «Рис 150 г и куриная грудка 120 г». Gemini помогает распознать блюдо, FatSecret предоставляет данные о продуктах и принимает запись. Результат может быть неточным; это не медицинская рекомендация. Только для пользователей 18+.\n\nКонфиденциальность: /privacy · Условия: /terms",
        "setup": "Подключите FatSecret — туда будут сохраняться подтверждённые записи о еде. Используя данные FatSecret, вы соглашаетесь с <a href=\"https://platform.fatsecret.com/terms\">условиями FatSecret Platform API</a>.\n\n<a href=\"https://platform.fatsecret.com\">Powered by fatsecret Platform API</a>",
        "setup_again": "После настройки отправьте блюдо ещё раз.",
        "input": "Что вы ели?\n\nОтправьте фото блюда, описание текстом или фото с подписью.\n\nПример: «Два яйца и тост с сыром».\nПодпись к фото: «Паста с курицей, около 300 г».\n\nМожно указать вес, ингредиенты и размер порции. Для отмены нажмите «Отменить добавление».",
        "choose_meal": "К какому приёму пищи добавить это блюдо?",
        "meal_reminder": "Выберите приём пищи кнопками под сообщением выше или отмените добавление.",
        "confirm_reminder": "Нажмите «Мне есть 18 — распознать», «Отправить другое» или «Отменить добавление» под текущим запросом.",
        "confirm_prefix": "Проверьте данные\n\nПриём пищи: {meal}\nОписание: ",
        "no_description": "Использую фотографию без дополнительного описания.",
        "confirm_suffix": "\n\nНажимая «Мне есть 18 — распознать», вы подтверждаете возраст и соглашаетесь передать фото или описание в Gemini для анализа. Запись в FatSecret начнётся только после отдельного подтверждения результата.",
        "download_error": "Не удалось загрузить фотографию. Отправьте её ещё раз или опишите блюдо текстом.",
        "input_error": "Отправьте фото блюда или напишите, что вы ели. Например: «Овсянка 200 г и банан».",
        "analysis": "Распознаю блюдо…", "search": "Подбираю продукты в FatSecret…",
        "saving": "Сохраняю записи в дневник…",
        "success": "Записи добавлены в FatSecret.\nПриём пищи: {meal}.",
        "not_food": "Не удалось найти еду в сообщении. Отправьте фото блюда или напишите, что вы ели.",
        "too_complex": "В сообщении слишком много отдельных блюд. Добавьте их несколькими запросами.",
        "uncertain": "Не удалось уверенно определить блюдо. Пришлите более чёткое фото или уточните название и состав.",
        "analysis_error": "Не удалось завершить обработку. Черновик удалён. Если запись уже началась, сначала проверьте дневник FatSecret. Затем отправьте фото или описание заново.",
        "access_error": "Сервис распознавания сейчас недоступен. Попробуйте позже.",
        "entry_error": "FatSecret вернул ошибку при сохранении. Проверьте дневник перед повторной отправкой.",
        "partial_error": "Добавлено {success} из {total} записей. Часть продуктов сохранить не удалось. Проверьте дневник перед повторным добавлением.",
        "review_title": "<b>Проверьте результат перед записью</b>",
        "review_meal": "Приём пищи: {meal}",
        "review_serving": "Порция FatSecret: {serving}",
        "review_serving_unknown": "описание порции отсутствует",
        "review_quantity": "Количество для записи: {value} {unit}",
        "review_mass": "Расчётная масса: {mass} г",
        "review_macros": "КБЖУ: {calories} ккал · Б {protein} г · Ж {fat} г · У {carbs} г",
        "review_total": "<b>Итого:</b> {calories} ккал · Б {protein} г · Ж {fat} г · У {carbs} г",
        "review_warning": "Распознавание и расчёты могут быть неточными. Сверьте продукты, порции и КБЖУ. Это не медицинская рекомендация.",
        "fatsecret_attribution": "<a href=\"https://platform.fatsecret.com\">Powered by fatsecret Platform API</a>",
        "review_reminder": "Проверьте результат и нажмите «Записать в FatSecret» или «Отменить добавление» под сообщением выше.",
        "review_unavailable": "Этот результат уже обработан, отменён или устарел. Отправьте блюдо заново, если хотите начать новую операцию.",
        "write_already_processed": "Повторная запись заблокирована. Проверьте дневник FatSecret перед новой попыткой.",
        "write_start_failed": "Не удалось безопасно начать запись. В FatSecret ничего не отправлено. Отправьте блюдо заново позже.",
        "write_partial_header": "Запись завершена частично. Повторная отправка автоматически не выполняется.",
        "write_succeeded": "<b>Добавлено:</b>\n{foods}",
        "write_failed": "<b>FatSecret отклонил:</b>\n{foods}",
        "write_uncertain": "<b>Результат записи не подтверждён:</b>\n{foods}\nПроверьте дневник FatSecret перед повторной попыткой.",
        "write_all_failed": "FatSecret отклонил все записи:\n{foods}",
        "meal_cancelled": "Добавление отменено.",
        "auth_steps": "Подключение FatSecret\n\n1. Нажмите «Открыть FatSecret».\n2. Войдите в аккаунт и разрешите доступ.\n3. Скопируйте полученный код и отправьте его в этот чат.\n\nПередавайте только код, без пояснений.",
        "auth_error": "Не удалось подключить FatSecret. Проверьте код и попробуйте ещё раз.",
        "auth_start_error": "Не удалось открыть подключение FatSecret. Попробуйте позже.",
        "auth_expired": "Подключение устарело. Начните его заново кнопкой «Подключить FatSecret».",
        "auth_success": "FatSecret подключён. Можно добавить первое блюдо.",
        "auth_reminder": "Отправьте код с сайта FatSecret текстом. Для отмены подключения отправьте /cancel.",
        "settings": "Настройки\n\nЯзык: Русский\nFatSecret: {connection}.",
        "disconnect_confirm": "Отключить FatSecret?\n\nБот больше не сможет добавлять еду, пока вы не подключите аккаунт снова. Записи в дневнике сохранятся.",
        "disconnect_error": "Не удалось отключить FatSecret. Попробуйте позже.",
        "user_error": "Не удалось загрузить профиль. Попробуйте открыть главное меню ещё раз.",
    },
    "en": {
        "matching_uncertain": "Could not reliably match the food and portion in FatSecret. Nothing was saved. Send the meal again with its name, brand and weight.",
        "meal_expired": "The meal draft has been removed. Send a photo or description again.",
        "daily_limit_reached": "You have reached today's meal processing limit. Please try again tomorrow.\n\nYour draft is kept for another 30 minutes of waiting. After that, send it again.",
        "service_retry": "The analysis service is temporarily busy. I will wait and retry automatically: attempt {attempt} of {total}.",
        "service_busy": "The analysis service is temporarily busy or its request limit has been reached. Automatic retries did not help. Nothing was saved to FatSecret.\n\nYour draft is kept for another 30 minutes of waiting. Try Recognize and add later, or cancel the meal.",
        "add": "Add meal", "menu_button": "Main menu", "settings_button": "Settings",
        "cancel_meal": "Cancel meal",
        "approve": "I am 18+ — recognize", "resend": "Send another",
        "write_entries": "Save to FatSecret",
        "breakfast": "Breakfast", "lunch": "Lunch", "dinner": "Dinner", "other": "Snack",
        "connect": "Connect FatSecret", "open_fatsecret": "Open FatSecret",
        "disconnect": "Disconnect FatSecret", "disconnect_yes": "Disconnect",
        "disconnect_no": "Keep connected", "language_button": "Language",
        "connected": "connected", "disconnected": "not connected",
        "menu": "Main menu\n\nSend a photo, a meal description, or a photo with a caption. After analysis, check the products, portions and macros, then confirm the diary write separately.\n\nExample: “150 g rice and 120 g chicken breast”. Gemini helps recognize the meal; FatSecret provides food data and receives the diary entry. Results may be inaccurate and are not medical advice. For users aged 18 and over.\n\nPrivacy: /privacy · Terms: /terms",
        "setup": "Connect FatSecret to save confirmed food diary entries. By using FatSecret data, you agree to the <a href=\"https://platform.fatsecret.com/terms\">fatsecret Platform API Terms</a>.\n\n<a href=\"https://platform.fatsecret.com\">Powered by fatsecret Platform API</a>",
        "setup_again": "Send your meal again after setup.",
        "input": "What did you eat?\n\nSend a meal photo, a text description, or a photo with a caption.\n\nExample: “Two eggs and toast with cheese”.\nPhoto caption: “Pasta with chicken, about 300 g”.\n\nYou can include weight, ingredients, and portion size. Press Cancel meal to stop.",
        "choose_meal": "Which meal should this food be added to?",
        "meal_reminder": "Choose a meal using the buttons below the previous message, or cancel the meal.",
        "confirm_reminder": "Press I am 18+ — recognize, Send another, or Cancel meal below the current request.",
        "confirm_prefix": "Check the details\n\nMeal: {meal}\nDescription: ",
        "no_description": "Using the photo without an additional description.",
        "confirm_suffix": "\n\nBy pressing I am 18+ — recognize, you confirm your age and agree to send the photo or description to Gemini for analysis. Nothing is written to FatSecret until you confirm the result separately.",
        "download_error": "Could not download the photo. Send it again or describe your meal in text.",
        "input_error": "Send a meal photo or describe what you ate. For example: “200 g oatmeal and a banana”.",
        "analysis": "Recognizing your meal…", "search": "Finding matching foods in FatSecret…",
        "saving": "Saving entries to your diary…",
        "success": "Entries added to FatSecret.\nMeal: {meal}.",
        "not_food": "Could not find food in your message. Send a meal photo or describe what you ate.",
        "too_complex": "There are too many separate dishes in this message. Add them in separate requests.",
        "uncertain": "Could not confidently identify the meal. Send a clearer photo or provide its name and ingredients.",
        "analysis_error": "Could not finish processing. The draft has been removed. If saving had already started, check your FatSecret diary first. Then send a photo or description again.",
        "access_error": "The recognition service is currently unavailable. Please try later.",
        "entry_error": "FatSecret returned an error while saving. Check your diary before sending the request again.",
        "partial_error": "Added {success} of {total} entries. Some foods could not be saved. Check your diary before adding them again.",
        "review_title": "<b>Check the result before saving</b>",
        "review_meal": "Meal: {meal}",
        "review_serving": "FatSecret serving: {serving}",
        "review_serving_unknown": "serving description unavailable",
        "review_quantity": "Quantity to save: {value} {unit}",
        "review_mass": "Estimated mass: {mass} g",
        "review_macros": "Macros: {calories} kcal · P {protein} g · F {fat} g · C {carbs} g",
        "review_total": "<b>Total:</b> {calories} kcal · P {protein} g · F {fat} g · C {carbs} g",
        "review_warning": "Recognition and calculations may be inaccurate. Check the products, portions and macros. This is not medical advice.",
        "fatsecret_attribution": "<a href=\"https://platform.fatsecret.com\">Powered by fatsecret Platform API</a>",
        "review_reminder": "Check the result and press Save to FatSecret or Cancel meal below the message above.",
        "review_unavailable": "This result has already been processed, cancelled, or expired. Send the meal again to start a new operation.",
        "write_already_processed": "A duplicate write was blocked. Check your FatSecret diary before trying again.",
        "write_start_failed": "The write could not be started safely. Nothing was sent to FatSecret. Send the meal again later.",
        "write_partial_header": "The write completed partially. Nothing will be retried automatically.",
        "write_succeeded": "<b>Added:</b>\n{foods}",
        "write_failed": "<b>Rejected by FatSecret:</b>\n{foods}",
        "write_uncertain": "<b>Write outcome not confirmed:</b>\n{foods}\nCheck your FatSecret diary before trying again.",
        "write_all_failed": "FatSecret rejected every entry:\n{foods}",
        "meal_cancelled": "Meal cancelled.",
        "auth_steps": "Connect FatSecret\n\n1. Press Open FatSecret.\n2. Sign in and allow access.\n3. Copy the code you receive and send it to this chat.\n\nSend only the code, without explanations.",
        "auth_error": "Could not connect FatSecret. Check the code and try again.",
        "auth_start_error": "Could not start the FatSecret connection. Please try later.",
        "auth_expired": "This connection has expired. Press Connect FatSecret to start again.",
        "auth_success": "FatSecret is connected. You can add your first meal.",
        "auth_reminder": "Send the code from FatSecret as text. Send /cancel to cancel the connection.",
        "settings": "Settings\n\nLanguage: English\nFatSecret: {connection}.",
        "disconnect_confirm": "Disconnect FatSecret?\n\nThe bot will not be able to add meals until you reconnect. Your diary entries will remain.",
        "disconnect_error": "Could not disconnect FatSecret. Please try later.",
        "user_error": "Could not load your profile. Try opening the main menu again.",
    },
}


def text(language: str, key: str, **values) -> str:
    return TEXTS.get(language, TEXTS["ru"])[key].format(**values)
