"""User-facing copy. Callback identifiers are independent of translated labels."""

HELLO = (
    "👋 <b>Добро пожаловать!</b>\n\n"
    "Я помогу распознать блюдо по фотографии или описанию, подобрать продукты в FatSecret "
    "и добавить их в дневник после вашего подтверждения.\n\n"
    "Выберите язык.\n\n"
    "Сервис предназначен для пользователей старше 18 лет.\n\n"
    "👋 <b>Welcome!</b>\n\n"
    "I can recognize a meal from a photo or description, match it with foods in FatSecret, "
    "and add it to your diary after your confirmation.\n\n"
    "Choose your language.\n\n"
    "This service is intended for users aged 18 and over."
)
LANGUAGE_PROMPT = "<b>Выберите язык / Choose your language</b>"

TEXTS = {
    "ru": {
        "matching_uncertain": "Не удалось надёжно подобрать продукт и порцию в FatSecret.\n\nНичего не записано. Отправьте блюдо ещё раз и по возможности укажите название, бренд и вес.",
        "meal_expired": "Время ожидания истекло, поэтому черновик блюда был удалён.\n\nОтправьте фотографию или описание ещё раз.",
        "daily_limit_reached": "На сегодня использованы все {limit} распознавания. Попробуйте снова завтра.\n\nТекущий черновик будет доступен до окончания 30-минутного срока хранения.",
        "usage_remaining": "📊 Сегодня осталось: {remaining} из {limit} распознаваний.",
        "service_retry": "Сервис анализа временно перегружен.\n\nПовторяю запрос автоматически: попытка {attempt} из {total}…",
        "service_busy": "Сервис анализа временно перегружен или достигнут лимит запросов.\n\nАвтоматические повторы не помогли. В FatSecret ничего не записано.\n\nЧерновик пока сохранён — вы можете повторить попытку позже или отменить добавление.",
        "add": "➕ Добавить блюдо", "menu_button": "Главное меню", "settings_button": "⚙️ Настройки",
        "back_to_main": "← Вернуться на главную",
        "cancel_meal": "Отменить",
        "approve": "✅ Подтвердить и распознать", "resend": "Отправить другое",
        "write_entries": "✅ Записать в FatSecret",
        "breakfast": "Завтрак", "lunch": "Обед", "dinner": "Ужин", "other": "Перекус",
        "connect": "🔗 Подключить FatSecret", "open_fatsecret": "Открыть FatSecret ↗",
        "disconnect": "Отключить FatSecret", "disconnect_yes": "Отключить",
        "disconnect_no": "Назад", "language_button": "🌐 Изменить язык",
        "connected": "подключён", "disconnected": "не подключён",
        "menu": "<b>Дневник питания</b>\n\nОтправьте фотографию блюда или опишите его текстом. Я распознаю состав, подберу продукты в FatSecret и покажу результат перед записью.\n\nНапример: «Рис 150 г и куриная грудка 120 г».\n\nРезультат распознавания может быть неточным и не является медицинской рекомендацией.\n\nКонфиденциальность: /privacy · Условия: /terms",
        "setup": "<b>Подключите FatSecret</b>\n\nПосле подключения бот сможет добавлять подтверждённые блюда в ваш дневник питания.\n\nИспользуя данные FatSecret, вы соглашаетесь с <a href=\"https://platform.fatsecret.com/terms\">условиями FatSecret Platform API</a>.\n\n<a href=\"https://platform.fatsecret.com\">Powered by fatsecret Platform API</a>",
        "setup_again": "Подключите FatSecret, а затем отправьте блюдо ещё раз.",
        "input": "<b>Что вы ели?</b>\n\nОтправьте фотографию блюда, описание текстом или фотографию с подписью.\n\n<b>Чтобы результат был точнее:</b>\n\n• укажите название блюда;\n• добавьте примерный вес или размер порции;\n• перечислите основные ингредиенты;\n• укажите бренд, если это готовый продукт;\n• фотографируйте блюдо целиком при хорошем освещении.\n\n✅ <b>Хороший пример</b>\n<blockquote>Гречка 150 г, куриная грудка 120 г и салат из огурцов и помидоров без масла.</blockquote>\n\n❌ <b>Плохой пример</b>\n<blockquote>Мой обед.</blockquote>",
        "choose_meal": "<b>Выберите приём пищи</b>\n\nКуда добавить это блюдо?",
        "meal_reminder": "Выберите приём пищи с помощью кнопок под предыдущим сообщением или нажмите «Отменить».",
        "confirm_reminder": "Выберите действие с помощью кнопок под сообщением с вашим блюдом.",
        "confirm_prefix": "<b>Проверьте данные</b>\n\nПриём пищи: {meal}\nОписание: ",
        "no_description": "Фотография без дополнительного описания",
        "confirm_suffix": "\n\nНажимая «Подтвердить и распознать», вы подтверждаете, что вам исполнилось 18 лет, и соглашаетесь передать фотографию или описание в Google Gemini для анализа.\n\nВ FatSecret ничего не будет записано без отдельного подтверждения результата.",
        "download_error": "Не удалось загрузить фотографию. Отправьте её ещё раз или опишите блюдо текстом.",
        "input_error": "Отправьте фото блюда или напишите, что вы ели. Например: «Овсянка 200 г и банан».",
        "analysis": "🔍 Распознаю блюдо…", "search": "🔍 Подбираю продукты в FatSecret…",
        "saving": "Сохраняю блюдо в FatSecret…",
        "success": "✅ <b>Блюдо добавлено в FatSecret</b>\n\n<b>Приём пищи:</b> {meal}",
        "not_food": "Не удалось найти еду в сообщении. Отправьте фото блюда или напишите, что вы ели.",
        "too_complex": "В сообщении слишком много отдельных блюд. Добавьте их несколькими запросами.",
        "uncertain": "Не удалось уверенно определить блюдо. Пришлите более чёткое фото или уточните название и состав.",
        "analysis_error": "Не удалось завершить обработку. Черновик удалён. Если запись уже началась, сначала проверьте дневник FatSecret. Затем отправьте фото или описание заново.",
        "access_error": "Сервис распознавания сейчас недоступен. Попробуйте позже.",
        "entry_error": "FatSecret вернул ошибку при сохранении. Проверьте дневник перед повторной отправкой.",
        "partial_error": "Добавлено {success} из {total} записей. Часть продуктов сохранить не удалось. Проверьте дневник перед повторным добавлением.",
        "review_title": "<b>Проверьте блюдо перед записью</b>",
        "review_meal": "<b>Приём пищи:</b> {meal}",
        "review_serving": "Порция FatSecret: {serving}",
        "review_serving_unknown": "описание порции отсутствует",
        "review_quantity": "Количество: {value} {unit}",
        "review_mass": "Расчётная масса: {mass} г",
        "review_macros": "КБЖУ: {calories} ккал · Б {protein} г · Ж {fat} г · У {carbs} г",
        "review_total": "<b>Итого:</b> {calories} ккал · Б {protein} г · Ж {fat} г · У {carbs} г",
        "review_warning": "⚠️ Распознавание и расчёты могут быть неточными. Проверьте продукты, порции и КБЖУ перед записью. Это не медицинская рекомендация.",
        "fatsecret_attribution": "<a href=\"https://platform.fatsecret.com\">Powered by fatsecret Platform API</a>",
        "review_reminder": "Проверьте результат и выберите действие с помощью кнопок под предыдущим сообщением.",
        "review_unavailable": "Этот результат уже обработан, отменён или устарел.\n\nОтправьте блюдо ещё раз, чтобы начать новую операцию.",
        "write_already_processed": "Эта операция уже была обработана.\n\nПовторная запись заблокирована. Проверьте дневник FatSecret перед новой попыткой.",
        "write_start_failed": "Не удалось безопасно начать запись.\n\nВ FatSecret ничего не отправлено. Попробуйте добавить блюдо ещё раз позже.",
        "write_partial_header": "⚠️ <b>Блюдо добавлено частично</b>\n\nПовторная отправка не выполняется автоматически.",
        "write_succeeded": "<b>Добавлено:</b>\n{foods}",
        "write_failed": "<b>Не удалось добавить:</b>\n{foods}",
        "write_uncertain": "⚠️ <b>Не удалось подтвердить результат записи:</b>\n{foods}\n\nFatSecret мог принять запрос, даже если бот не получил ответ. Проверьте дневник перед повторной попыткой.",
        "write_all_failed": "❌ <b>Не удалось добавить блюдо</b>\n\nFatSecret отклонил следующие записи:\n\n{foods}",
        "meal_cancelled": "Добавление блюда отменено.",
        "auth_steps": "<b>Подключение FatSecret</b>\n\n1. Нажмите «Открыть FatSecret».\n2. Войдите в свой аккаунт и разрешите доступ.\n3. Скопируйте полученный код и отправьте его в этот чат.\n\nОтправьте только код, без дополнительного текста.",
        "auth_error": "Не удалось подключить FatSecret. Проверьте код и попробуйте ещё раз.",
        "auth_start_error": "Не удалось открыть подключение FatSecret. Попробуйте позже.",
        "auth_expired": "Время подключения истекло.\n\nНачните авторизацию заново через кнопку «Подключить FatSecret».",
        "auth_success": "✅ <b>FatSecret подключён</b>\n\nТеперь можно добавить первое блюдо.",
        "auth_reminder": "Отправьте код с сайта FatSecret обычным текстовым сообщением.\n\nЧтобы отменить подключение, отправьте /cancel.",
        "settings": "<b>Настройки</b>\n\nЯзык: Русский\nFatSecret: {connection}",
        "disconnect_confirm": "<b>Отключить FatSecret?</b>\n\nБот не сможет добавлять блюда, пока вы снова не подключите аккаунт.\n\nУже добавленные записи останутся в дневнике FatSecret.",
        "disconnect_error": "Не удалось отключить FatSecret. Попробуйте позже.",
        "user_error": "Не удалось загрузить профиль. Попробуйте открыть главное меню ещё раз.",
    },
    "en": {
        "matching_uncertain": "Could not reliably match the food and serving in FatSecret.\n\nNothing was saved. Send the meal again and include its name, brand, and weight if possible.",
        "meal_expired": "The waiting period has ended, so the meal draft was removed.\n\nSend a photo or description again.",
        "daily_limit_reached": "You have used all {limit} recognitions available today. Please try again tomorrow.\n\nThe current draft will remain available until its 30-minute storage period ends.",
        "usage_remaining": "📊 Recognitions left today: {remaining} of {limit}.",
        "service_retry": "The analysis service is temporarily busy.\n\nRetrying automatically: attempt {attempt} of {total}…",
        "service_busy": "The analysis service is temporarily busy or its request limit has been reached.\n\nAutomatic retries did not help. Nothing was saved to FatSecret.\n\nYour draft is still available — you can try again later or cancel the meal.",
        "add": "➕ Add meal", "menu_button": "Main menu", "settings_button": "⚙️ Settings",
        "back_to_main": "← Back to main menu",
        "cancel_meal": "Cancel",
        "approve": "✅ Confirm and recognize", "resend": "Send another",
        "write_entries": "✅ Save to FatSecret",
        "breakfast": "Breakfast", "lunch": "Lunch", "dinner": "Dinner", "other": "Snack",
        "connect": "🔗 Connect FatSecret", "open_fatsecret": "Open FatSecret ↗",
        "disconnect": "Disconnect FatSecret", "disconnect_yes": "Disconnect",
        "disconnect_no": "Back", "language_button": "🌐 Change language",
        "connected": "connected", "disconnected": "not connected",
        "menu": "<b>Food diary</b>\n\nSend a photo of your meal or describe it in text. I will recognize the ingredients, find matching foods in FatSecret, and show you the result before saving.\n\nFor example: “150 g rice and 120 g chicken breast”.\n\nRecognition results may be inaccurate and are not medical advice.\n\nPrivacy: /privacy · Terms: /terms",
        "setup": "<b>Connect FatSecret</b>\n\nOnce connected, the bot can add confirmed meals to your food diary.\n\nBy using FatSecret data, you agree to the <a href=\"https://platform.fatsecret.com/terms\">fatsecret Platform API Terms</a>.\n\n<a href=\"https://platform.fatsecret.com\">Powered by fatsecret Platform API</a>",
        "setup_again": "Connect FatSecret, then send your meal again.",
        "input": "<b>What did you eat?</b>\n\nSend a meal photo, a text description, or a photo with a caption.\n\n<b>For a more accurate result:</b>\n\n• include the name of the meal;\n• add the approximate weight or portion size;\n• list the main ingredients;\n• include the brand for packaged foods;\n• photograph the entire meal in good lighting.\n\n✅ <b>Good example</b>\n<blockquote>150 g buckwheat, 120 g chicken breast, and a cucumber and tomato salad without dressing.</blockquote>\n\n❌ <b>Poor example</b>\n<blockquote>My lunch.</blockquote>",
        "choose_meal": "<b>Choose a meal</b>\n\nWhere should this food be added?",
        "meal_reminder": "Choose a meal using the buttons below the previous message, or press Cancel.",
        "confirm_reminder": "Choose an action using the buttons below the message with your meal.",
        "confirm_prefix": "<b>Check the details</b>\n\nMeal: {meal}\nDescription: ",
        "no_description": "Photo without an additional description",
        "confirm_suffix": "\n\nBy pressing “Confirm and recognize”, you confirm that you are at least 18 years old and agree to send the photo or description to Google Gemini for analysis.\n\nNothing will be saved to FatSecret until you separately confirm the result.",
        "download_error": "Could not download the photo. Send it again or describe your meal in text.",
        "input_error": "Send a meal photo or describe what you ate. For example: “200 g oatmeal and a banana”.",
        "analysis": "🔍 Recognizing your meal…", "search": "🔍 Finding matching foods in FatSecret…",
        "saving": "Saving your meal to FatSecret…",
        "success": "✅ <b>Meal added to FatSecret</b>\n\n<b>Meal:</b> {meal}",
        "not_food": "Could not find food in your message. Send a meal photo or describe what you ate.",
        "too_complex": "There are too many separate dishes in this message. Add them in separate requests.",
        "uncertain": "Could not confidently identify the meal. Send a clearer photo or provide its name and ingredients.",
        "analysis_error": "Could not finish processing. The draft has been removed. If saving had already started, check your FatSecret diary first. Then send a photo or description again.",
        "access_error": "The recognition service is currently unavailable. Please try later.",
        "entry_error": "FatSecret returned an error while saving. Check your diary before sending the request again.",
        "partial_error": "Added {success} of {total} entries. Some foods could not be saved. Check your diary before adding them again.",
        "review_title": "<b>Check the meal before saving</b>",
        "review_meal": "<b>Meal:</b> {meal}",
        "review_serving": "FatSecret serving: {serving}",
        "review_serving_unknown": "serving description unavailable",
        "review_quantity": "Quantity: {value} {unit}",
        "review_mass": "Estimated mass: {mass} g",
        "review_macros": "Macros: {calories} kcal · P {protein} g · F {fat} g · C {carbs} g",
        "review_total": "<b>Total:</b> {calories} kcal · P {protein} g · F {fat} g · C {carbs} g",
        "review_warning": "⚠️ Recognition and calculations may be inaccurate. Check the foods, portions, and macros before saving. This is not medical advice.",
        "fatsecret_attribution": "<a href=\"https://platform.fatsecret.com\">Powered by fatsecret Platform API</a>",
        "review_reminder": "Check the result and choose an action using the buttons below the previous message.",
        "review_unavailable": "This result has already been processed, cancelled, or expired.\n\nSend the meal again to start a new operation.",
        "write_already_processed": "This operation has already been processed.\n\nA duplicate write was blocked. Check your FatSecret diary before trying again.",
        "write_start_failed": "The write could not be started safely.\n\nNothing was sent to FatSecret. Try adding the meal again later.",
        "write_partial_header": "⚠️ <b>Meal added partially</b>\n\nNothing will be retried automatically.",
        "write_succeeded": "<b>Added:</b>\n{foods}",
        "write_failed": "<b>Could not add:</b>\n{foods}",
        "write_uncertain": "⚠️ <b>The write result could not be confirmed:</b>\n{foods}\n\nFatSecret may have accepted the request even though the bot did not receive a response. Check your diary before trying again.",
        "write_all_failed": "❌ <b>Could not add the meal</b>\n\nFatSecret rejected the following entries:\n\n{foods}",
        "meal_cancelled": "Meal addition cancelled.",
        "auth_steps": "<b>Connect FatSecret</b>\n\n1. Press “Open FatSecret”.\n2. Sign in to your account and allow access.\n3. Copy the code and send it to this chat.\n\nSend only the code, without any additional text.",
        "auth_error": "Could not connect FatSecret. Check the code and try again.",
        "auth_start_error": "Could not start the FatSecret connection. Please try later.",
        "auth_expired": "The connection period has expired.\n\nStart authorization again using the Connect FatSecret button.",
        "auth_success": "✅ <b>FatSecret connected</b>\n\nYou can now add your first meal.",
        "auth_reminder": "Send the code from the FatSecret website as a plain text message.\n\nTo cancel the connection, send /cancel.",
        "settings": "<b>Settings</b>\n\nLanguage: English\nFatSecret: {connection}",
        "disconnect_confirm": "<b>Disconnect FatSecret?</b>\n\nThe bot will not be able to add meals until you reconnect your account.\n\nEntries already added to your FatSecret diary will remain there.",
        "disconnect_error": "Could not disconnect FatSecret. Please try later.",
        "user_error": "Could not load your profile. Try opening the main menu again.",
    },
}


def text(language: str, key: str, **values) -> str:
    return TEXTS.get(language, TEXTS["ru"])[key].format(**values)
