"""User-facing copy. Callback identifiers are independent of translated labels."""

HELLO = (
    "Привет! Я помогу добавлять еду в дневник FatSecret по фото или описанию.\nВыберите язык.\n\n"
    "Hi! I can add meals to your FatSecret diary from a photo or description.\nChoose your language."
)
LANGUAGE_PROMPT = "Выберите язык / Choose your language:"

TEXTS = {
    "ru": {
        "daily_limit_reached": "На сегодня лимит добавлений исчерпан. Попробуйте снова завтра.\n\nФото, описание и приём пищи сохранены.",
        "service_retry": "Сервис анализа временно перегружен. Подожду и повторю запрос автоматически: попытка {attempt} из {total}.",
        "service_busy": "Сервис анализа временно перегружен или достигнут лимит запросов. Автоматические повторы не помогли. В FatSecret ничего не записано.\n\nФото, описание и приём пищи сохранены. Попробуйте позже кнопкой «Распознать и добавить» или отмените добавление.",
        "add": "Добавить еду", "menu_button": "Главное меню", "settings_button": "Настройки",
        "cancel_meal": "Отменить добавление",
        "approve": "Распознать и добавить", "resend": "Отправить другое",
        "breakfast": "Завтрак", "lunch": "Обед", "dinner": "Ужин", "other": "Перекус",
        "connect": "Подключить FatSecret", "open_fatsecret": "Открыть FatSecret",
        "disconnect": "Отключить FatSecret", "disconnect_yes": "Отключить",
        "disconnect_no": "Оставить подключённым", "language_button": "Язык",
        "connected": "подключён", "disconnected": "не подключён",
        "menu": "Главное меню\n\nОтправьте фото, описание блюда или фото с подписью. Затем выберите приём пищи и нажмите «Распознать и добавить».\n\nПример: «Рис 150 г и куриная грудка 120 г». Вес и размер порции помогут точнее распознать блюдо.",
        "setup": "Подключите FatSecret — туда будут сохраняться записи о еде. Нажмите «Подключить FatSecret», затем следуйте инструкции.",
        "setup_again": "После настройки отправьте блюдо ещё раз.",
        "input": "Что вы ели?\n\nОтправьте фото блюда, описание текстом или фото с подписью.\n\nПример: «Два яйца и тост с сыром».\nПодпись к фото: «Паста с курицей, около 300 г».\n\nМожно указать вес, ингредиенты и размер порции. Для отмены нажмите «Отменить добавление».",
        "choose_meal": "К какому приёму пищи добавить это блюдо?",
        "meal_reminder": "Выберите приём пищи кнопками под сообщением выше или отмените добавление.",
        "confirm_reminder": "Нажмите «Распознать и добавить», «Отправить другое» или «Отменить добавление» под текущим запросом.",
        "confirm_prefix": "Проверьте данные\n\nПриём пищи: {meal}\nОписание: ",
        "no_description": "Использую фотографию без дополнительного описания.",
        "confirm_suffix": "\n\nНажмите «Распознать и добавить». Я определю продукты и сохраню их в FatSecret.",
        "download_error": "Не удалось загрузить фотографию. Отправьте её ещё раз или опишите блюдо текстом.",
        "input_error": "Отправьте фото блюда или напишите, что вы ели. Например: «Овсянка 200 г и банан».",
        "analysis": "Распознаю блюдо…", "search": "Подбираю продукты в FatSecret…",
        "saving": "Сохраняю записи в дневник…",
        "success": "Записи добавлены в FatSecret.\nПриём пищи: {meal}.",
        "not_food": "Не удалось найти еду в сообщении. Отправьте фото блюда или напишите, что вы ели.",
        "too_complex": "В сообщении слишком много отдельных блюд. Добавьте их несколькими запросами.",
        "uncertain": "Не удалось уверенно определить блюдо. Пришлите более чёткое фото или уточните название и состав.",
        "analysis_error": "Не удалось завершить обработку. Попробуйте ещё раз или отправьте другое описание. Если запись уже началась, сначала проверьте дневник FatSecret.",
        "access_error": "Сервис распознавания сейчас недоступен. Попробуйте позже.",
        "entry_error": "FatSecret вернул ошибку при сохранении. Проверьте дневник перед повторной отправкой.",
        "partial_error": "Добавлено {success} из {total} записей. Часть продуктов сохранить не удалось. Проверьте дневник перед повторным добавлением.",
        "meal_cancelled": "Добавление отменено.",
        "auth_steps": "Подключение FatSecret\n\n1. Нажмите «Открыть FatSecret».\n2. Войдите в аккаунт и разрешите доступ.\n3. Скопируйте полученный код и отправьте его в этот чат.\n\nПередавайте только код, без пояснений.",
        "auth_error": "Не удалось подключить FatSecret. Проверьте код и попробуйте ещё раз.",
        "auth_start_error": "Не удалось открыть подключение FatSecret. Попробуйте позже.",
        "auth_expired": "Подключение устарело. Начните его заново кнопкой «Подключить FatSecret».",
        "auth_success": "FatSecret подключён. Можно добавить первое блюдо.",
        "auth_reminder": "Отправьте код с сайта FatSecret текстом. Для отмены подключения отправьте /cancel.",
        "settings": "Настройки\n\nЯзык: Русский\nFatSecret: {connection}.",
        "disconnect_confirm": "Отключить FatSecret?\n\nБот больше не сможет добавлять еду, пока вы не подключите аккаунт снова. Записи в дневнике сохранятся.",
        "disconnect_error": "Не удалось отключить FatSecret. Попробуйте позже.",
        "user_error": "Не удалось загрузить профиль. Попробуйте открыть главное меню ещё раз.",
    },
    "en": {
        "daily_limit_reached": "You have reached today's meal processing limit. Please try again tomorrow.\n\nYour photo, description and meal selection are preserved.",
        "service_retry": "The analysis service is temporarily busy. I will wait and retry automatically: attempt {attempt} of {total}.",
        "service_busy": "The analysis service is temporarily busy or its request limit has been reached. Automatic retries did not help. Nothing was saved to FatSecret.\n\nYour photo, description and meal selection are preserved. Try Recognize and add later, or cancel the meal.",
        "add": "Add meal", "menu_button": "Main menu", "settings_button": "Settings",
        "cancel_meal": "Cancel meal",
        "approve": "Recognize and add", "resend": "Send another",
        "breakfast": "Breakfast", "lunch": "Lunch", "dinner": "Dinner", "other": "Snack",
        "connect": "Connect FatSecret", "open_fatsecret": "Open FatSecret",
        "disconnect": "Disconnect FatSecret", "disconnect_yes": "Disconnect",
        "disconnect_no": "Keep connected", "language_button": "Language",
        "connected": "connected", "disconnected": "not connected",
        "menu": "Main menu\n\nSend a photo, a meal description, or a photo with a caption. Choose a meal, then press Recognize and add.\n\nExample: “150 g rice and 120 g chicken breast”. Weight and portion size help identify your meal more accurately.",
        "setup": "Connect FatSecret to save your food diary entries. Press Connect FatSecret, then follow the instructions.",
        "setup_again": "Send your meal again after setup.",
        "input": "What did you eat?\n\nSend a meal photo, a text description, or a photo with a caption.\n\nExample: “Two eggs and toast with cheese”.\nPhoto caption: “Pasta with chicken, about 300 g”.\n\nYou can include weight, ingredients, and portion size. Press Cancel meal to stop.",
        "choose_meal": "Which meal should this food be added to?",
        "meal_reminder": "Choose a meal using the buttons below the previous message, or cancel the meal.",
        "confirm_reminder": "Press Recognize and add, Send another, or Cancel meal below the current request.",
        "confirm_prefix": "Check the details\n\nMeal: {meal}\nDescription: ",
        "no_description": "Using the photo without an additional description.",
        "confirm_suffix": "\n\nPress Recognize and add. I will identify the foods and save them to FatSecret.",
        "download_error": "Could not download the photo. Send it again or describe your meal in text.",
        "input_error": "Send a meal photo or describe what you ate. For example: “200 g oatmeal and a banana”.",
        "analysis": "Recognizing your meal…", "search": "Finding matching foods in FatSecret…",
        "saving": "Saving entries to your diary…",
        "success": "Entries added to FatSecret.\nMeal: {meal}.",
        "not_food": "Could not find food in your message. Send a meal photo or describe what you ate.",
        "too_complex": "There are too many separate dishes in this message. Add them in separate requests.",
        "uncertain": "Could not confidently identify the meal. Send a clearer photo or provide its name and ingredients.",
        "analysis_error": "Could not finish processing. Try again or send another description. If saving had already started, check your FatSecret diary first.",
        "access_error": "The recognition service is currently unavailable. Please try later.",
        "entry_error": "FatSecret returned an error while saving. Check your diary before sending the request again.",
        "partial_error": "Added {success} of {total} entries. Some foods could not be saved. Check your diary before adding them again.",
        "meal_cancelled": "Meal cancelled.",
        "auth_steps": "Connect FatSecret\n\n1. Press Open FatSecret.\n2. Sign in and allow access.\n3. Copy the code you receive and send it to this chat.\n\nSend only the code, without explanations.",
        "auth_error": "Could not connect FatSecret. Check the code and try again.",
        "auth_start_error": "Could not start the FatSecret connection. Please try later.",
        "auth_expired": "This connection has expired. Press Connect FatSecret to start again.",
        "auth_success": "FatSecret is connected. You can add your first meal.",
        "auth_reminder": "Send the code from FatSecret as text. Send /cancel to cancel the connection.",
        "settings": "Settings\n\nLanguage: English\nFatSecret: {connection}.",
        "disconnect_confirm": "Disconnect FatSecret?\n\nThe bot will not be able to add meals until you reconnect. Your diary entries will remain.",
        "disconnect_error": "Could not disconnect FatSecret. Please try later.",
        "user_error": "Could not load your profile. Try opening the main menu again.",
    },
}


def text(language: str, key: str, **values) -> str:
    return TEXTS.get(language, TEXTS["ru"])[key].format(**values)
